### ISSUE TITLE
run error in input2conv.m

### ISSUE THREAD

**Issue by xiaojidan** [vcnn/vcnn_double-bladed#1]
Hi @vcnn , I download your code, and run it. I find a problem, do you find it?
I run deapeaf_demo.m on win8 64bit, and a bug exists in line4 of the input2conv.m. which shows 'Error using gpuArray/bsxfun
Out of memory on device. To view more detail about available memory on the GPU, use 'gpuDevice()'. If the problem persists, reset the GPU by calling
'gpuDevice(1)'', But I set the GPU. I debug it, and find it occurs when n=3. 
Hope you help solve this problem. Thanks a lot!

**Comment by vcnn** [comment]
Thanks for the comment. What graphics card did you use? How much gpu memory?

**Comment by xiaojidan** [comment]
NVIDA, GeForce GT 650M. For gpu memory, TotalMemory: 2.1475e+09,  AvailableMemory: 1.7369e+09. What's wrong with my PC?

**Comment by vcnn** [comment]
If you have a GPU with 4GB memory, you can directly run the demo. If you have a GPU with memory less than 4GB and encounter an out of memory error, you may go to "applications/deep_edge_aware_filters/utility/prepare_net_filter.m" to make the "max_patch_size" variable smaller. By the way, did you tried other demos, e.g. MNIST and denoise. Did you install CUDA 6.0 or newer?

**Comment by xiaojidan** [comment]
Thanks a lot @vcnn . Other demos run ok. My PC with 8GB. I already install CUDA 6.0. I try it.

**Comment by vcnn** [comment]
Cool, let me know if adjust max_patch_size works.

**Comment by xiaojidan** [comment]
Wow!!!. It runs ok. I set max_patch_size=100. Thanks @vcnn . I guess that my PC is some troubles with GPU setting, so I encounter previous error.

**Comment by vcnn** [comment]
That's cool! @xiaojidan
